### ISSUE TITLE
4.16.2+ lightdm logon screen will not unblank after monitors fall asleep

### ISSUE THREAD

**Issue by usur-per** [M-Bab/linux-kernel-amdgpu-binaries#55] opened 2018-04-23 18:42 UTC
Again, submitted bug to freedesktop. Here's the link:

https://bugs.freedesktop.org/show_bug.cgi?id=106192

**Comment by M-Bab** [comment] 2018-04-23 21:40
Thanks for reporting all the stuff upstream at freedesktop. I reported this specific problem already a few times on the amdgpu developers mailing list. I still have hope that this is fixed one day.

**Comment by M-Bab** [comment] 2018-06-19 19:18
Can you recheck with the latest (4.17)?

**Comment by usur-per** [comment] 2018-06-19 19:35
I'll need to test this later on. Thanks!

**Comment by M-Bab** [comment] 2018-09-18 07:29
I think the issue is finally resolved. Didn't see the problem for months.

**Closed as completed by M-Bab** 2018-09-18 07:29 UTC

**Comment by usur-per** [comment] 2018-09-18 07:47
Hey m-bab. Yeah, you're correct. I'm running 4-17.0+ right now and have not run into the problem since upgrade. Thanks!
