### ISSUE TITLE
Completely random system lockups?

### ISSUE THREAD

**Issue by lillelilje** [M-Bab/linux-kernel-amdgpu-binaries#26] opened 2017-09-18 09:19 UTC
Hello and thank you very much for this.

It's great as it allows me to use my lovely Vega 56. The sad thing is that it seems to cause full system lock ups at completely random points. Sometimes it goes a full day without a crash, other times it takes 5 minutes before it freezes again.

Sound seems to keep working for a while during the crash as discord voice or music keeps playing for a while - but input and screen is completely frozen.

I'm unsure about what logs could potentially provide valuable information about these crashes.

```
$ uname -r
4.12.13+
```

Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
RX Vega 56

Please note, this happens both on 4.12.12 and 4.12.13

**Comment by dualbus** [comment] 2017-09-18 13:47
Do you see any kernel Oops report in /var/log/syslog?

Try with:

    awk '/ BUG: /,/ end trace /' /var/log/syslog*

And see if you have any stacktraces in there.

**Comment by lillelilje** [comment] 2017-09-18 13:52
Checked on two PCs that experience the exact same issue and there is nothing returned from that.

**Comment by M-Bab** [comment] 2017-09-18 15:54
Doesn't sound very enjoyable. But remember this is a bleeding edge kernel combined with a brand new GPU. And here go my usual questions for more information:

1. Which kernel version are you using? Vanilla or Ubuntu? Have you tried the other one?
2. Which is the oldest kernel where the problem started (if there was an older trouble-free kernel)?
3. Have you tried other mesa drivers?
4. The outputs of "dmesg | grep amdgpu", "lsmod | grep amdgpu", "dpkg -l | grep firmware" and "dpkg -l | grep mesa"

Since I can't reproduce this issue there are two options for you: The lazy one - keep updating the kernel until its hopefully fixed. The committed one: Try to help finding the cause of the problem.
For the latter approach you should test some other of my kernels. Vanilla vs. Ubuntu. The first 4.12 kernel, the last 4.11 kernel maybe even the 4.9 kernel. You can access older kernels via https://github.com/M-Bab/linux-kernel-amdgpu-binaries/commits/master and the "<>" button.

**Comment by lillelilje** [comment] 2017-09-18 16:08
> Doesn't sound very enjoyable. But remember this is a bleeding edge kernel combined with a brand new GPU

I'm not complaining at all to be honest, the fact that this works at all is phenomenal! Thank you very much for the kernel!

> Which kernel version are you using? Vanilla or Ubuntu? Have you tried the other one?

Ubuntu, I'll give vanilla a go!
> Which is the oldest kernel where the problem started (if there was an older trouble-free kernel)?

Sadly I've only been using this since saturday.

> Have you tried other mesa drivers?

As in different versions of mesa? Not entirely sure of what "mesa drivers" means, sadly.

> The outputs of "dmesg | grep amdgpu", "lsmod | grep amdgpu", "dpkg -l | grep firmware" and "dpkg -l | grep mesa"

https://gist.github.com/oleerik/3c3bb54733d7bbf47d103043803571ad

**Comment by lillelilje** [comment] 2017-09-20 07:19
A little, potentially too early, update:

Switched one machine to Vanilla and kept one on Ubuntu.
On top of that there was a libdrm-amdgpu update yesterday. 

Edited:
The machine still on the ubuntu kernel just had a full freeze, the other one hasn't had any other crashes.

**Comment by M-Bab** [comment] 2017-09-20 17:56
You can always test older kernels by looking at https://github.com/M-Bab/linux-kernel-amdgpu-binaries/commits/master and switching to an older commit with the <> button.

Other versions of mesa mean switching between the padoka and oibaf ppa (see README) or the padoka stable PPA (https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/pkppa/). They should all work but sometimes they can cause a crash as well.

**Comment by lillelilje** [comment] 2017-09-21 05:45
Haha, dealing with a llvm bug at the moment that stops us from testing at all :) I'll keep testing different versions when we can.

**Comment by lillelilje** [comment] 2017-10-14 15:59
Some mesa updates and kernel updates later, we are no longer experiencing this issue (it seems!)

**Closed as completed** 2017-10-16 15:38 UTC
