### ISSUE TITLE
Brightness output issue - I think someone may have patched for it in bugs.freedesktop.org

### ISSUE THREAD

**Issue by usur-per** [M-Bab/linux-kernel-amdgpu-binaries#53] opened 2018-04-23 18:40 UTC
Check it out

https://bugs.freedesktop.org/show_bug.cgi?id=106006

A note from one of the dev:

For DC developers: behind the scenes, brightness 1 means no-op/pass-through gamma LUT, lower brightness levels are simulated by modifying the gamma LUT accordingly.

I managed to get things looking alright with the following:

root@[uwutm8]~$ xrandr --output DP-6 --brightness .99

Sadly, every time the driver seems to be utilized (opening steam, strangely, connecting to my phone's USB fileshare link) causes all my monitors to reset back to their original "brightness 1" value.

**Comment by M-Bab** [comment] 2018-04-23 21:36
The patch Harry Wentland proposed on the freedesktop page is included in 4.16.3. Is it fixed now?

**Comment by M-Bab** [comment] 2018-04-23 21:42
I think these 3 issues are related:
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/49
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/51
https://github.com/M-Bab/linux-kernel-amdgpu-binaries/issues/53

So far I can't reproduce any of them so it is hard for me to help here.

**Comment by M-Bab** [comment] 2018-06-19 19:19
Can you recheck with 4.17?

**Comment by usur-per** [comment] 2018-06-19 19:45
This was fixed by 4.17.

Sorry again. I'll be sure to close these bug entries in the future. Thanks!

Bug page: https://bugs.freedesktop.org/show_bug.cgi?id=106006

**Closed as completed** 2018-06-19 19:46 UTC
